#!/usr/bin/env python
# -*- coding: iso-8859-1 -*-
# generated by wxGlade 0.6.3 on Mon Nov 15 10:19:42 2010

import wx
from cloudvibe.song import *

# begin wxGlade: extracode
# end wxGlade

class FileDropTarget(wx.FileDropTarget):
  """ Implements Drop Target functionality for Files """
  def __init__(self, fn):
    wx.FileDropTarget.__init__(self)
    self.fn = fn

  def OnDropFiles(self, x, y, filenames):
    self.fn(filenames)


class MyDialog(wx.Dialog):
  def __init__(self, *args, **kwds):
    # begin wxGlade: MyDialog.__init__
    kwds["style"] = wx.DEFAULT_DIALOG_STYLE
    wx.Dialog.__init__(self, *args, **kwds)

    self.songList = wx.ListCtrl(self, -1,
                                style=wx.LC_REPORT|wx.SUNKEN_BORDER)

    self.initListCtrl(self.songList)

    self.addSongButton = wx.Button(self, -1, "Add Song")
    self.okButton = wx.Button(self, wx.ID_OK, "")
    self.cancelButton = wx.Button(self, wx.ID_CANCEL, "")

    self.__set_properties()
    self.__do_layout()

    #self.Bind(wx.EVT_LIST_INSERT_ITEM, self.onInsertItem, self.songList)
    self.Bind(wx.EVT_BUTTON, self.handleAddSong, self.addSongButton)
    # end wxGlade

  def initListCtrl(self, l):
    l.InsertColumn(0, "Title");
    l.InsertColumn(1, "Artist");
    l.InsertColumn(2, "Album");

    # Add Drop handler
    dropTarget = FileDropTarget(self.onDropFiles)
    l.SetDropTarget(dropTarget)

  def __set_properties(self):
    # begin wxGlade: MyDialog.__set_properties
    self.SetTitle("Song Upload Prototype")
    self.SetSize(wx.DLG_SZE(self, (281, 195)))
    # end wxGlade

  def __do_layout(self):
    # begin wxGlade: MyDialog.__do_layout
    sizer_1 = wx.BoxSizer(wx.VERTICAL)
    sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
    sizer_1.Add(self.songList, 1, wx.EXPAND, 0)
    sizer_2.Add(self.addSongButton, 0, 0, 0)
    sizer_2.Add(self.okButton, 0, wx.LEFT, 10)
    sizer_2.Add(self.cancelButton, 0, wx.LEFT, 10)
    sizer_1.Add(sizer_2, 0, wx.ALL|wx.ALIGN_RIGHT, 11)
    self.SetSizer(sizer_1)
    self.Layout()
    # end wxGlade

  def onDropFiles(self, files):
    for file in files:
      song = Song(file)
      song.load_tags()
      self.addSong(song)

  def addSong(self, song):
    l = self.songList

    print song.title

    ind = l.GetItemCount()
    l.InsertStringItem(ind, song.title or song.filename)
    l.SetStringItem(ind, 1, song.artist)
    l.SetStringItem(ind, 2, song.album)

  def handleAddSong(self, event): # wxGlade: MyDialog.<event_handler>
    print "Event handler `handleAddSong' not implemented"
    event.Skip()

# end of class MyDialog


if __name__ == "__main__":
  app = wx.PySimpleApp(0)
  wx.InitAllImageHandlers()
  dialog_1 = MyDialog(None, -1, "")
  app.SetTopWindow(dialog_1)
  dialog_1.Show()
  app.MainLoop()
